# Generated by Django 5.2.5 on 2025-08-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="emotions_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
